config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  namespace :pages do
    resources :repository, only: :index
    resources :contact, only: :index
    resources :about, only: :index
  end

  # Defines the root path route ("/")
  root 'pages#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name terms_and_conditions])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/concerns/turbo_tag_setter.rb
# frozen_string_literal: true

module TurboTagSetter
  extend ActiveSupport::Concern

  def set_pages_content
    @pages_content = 'pages_content'
  end
end

app/controllers/pages/about_controller.rb
class Pages::AboutController < PagesController
  def index
    render partial: 'index', layout: false if turbo_frame_request?
  end
end

app/controllers/pages/contact_controller.rb
class Pages::ContactController < PagesController
  def index
    puts '<---- Pages::Contact ---->'
    puts @pages_content
    render partial: 'index', layout: false if turbo_frame_request?
  end
end

app/controllers/pages/repository_controller.rb
class Pages::RepositoryController < PagesController
  def index
    render partial: 'index', layout: false if turbo_frame_request?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include TurboTagSetter

  skip_before_action :authenticate_user!
  before_action :set_pages_content

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages/about_helper.rb
module Pages::AboutHelper
end

app/helpers/pages/contact_helper.rb
module Pages::ContactHelper
end

app/helpers/pages/repository_helper.rb
module Pages::RepositoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/_about.html.erb
<%= turbo_frame_tag @page do %>
  <!-- TODO: Implement about -->
  <p>Cheguei no about</p>
<% end %>

app/views/home/_contact.html.erb
<%= turbo_frame_tag @page do %>
  <!-- TODO: implement contact -->
  <p>Cheguei no contact</p>
<% end %>

app/views/home/_header.html.erb
<header class="bg-white border-b border-gray-200 dark:bg-gray-900 dark:border-gray-700 sticky top-0 z-50">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-4">
    <a href="/" class="flex items-center">
      <img src="/assets/anki-on-rails-logo.png" alt="Logo" class="h-8 mr-2">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Anki on Rails</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="/repository" data-turbo-frame="page" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Repository</a>
        </li>
        <li>
          <a href="/contact" data-turbo-frame="page" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
        </li>
        <li>
          <a href="/about" data-turbo-frame="page" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
        </li>
        <li>
          <% if current_user %>
            <a href="/logout" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Logout</a>
          <% else %>
            <a href="/login" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Login</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/home/_repository.html.erb
<%= turbo_frame_tag @page do %>
  <!-- TODO: Implementar repositório -->
  <p>Cheguei nos resources</p>
<% end %>

app/views/home/index.html.erb
<%= render 'home/header' %>

<%= turbo_frame_tag @page do %>
  <hero class="flex flex-col place-items-center">
   <h1 class="font-bold text-3xl mt-20 mb-8">Anki on Rails</h1>
   <h2 class="font-semibold text-6xl text-center"><%= t("home.hero_top") %></h2>
   <p class="text-2xl my-8 text-center"><%= t("home.hero_bottom") %></p>
   <%= link_to 'Get Started', new_user_session_path, class: 'inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition duration-150 ease-in-out' %>
  </hero>
<% end %>
<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnkiOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto px-4">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_header.html.erb
<header class="bg-white border-b border-gray-200 dark:bg-gray-900 dark:border-gray-700 sticky top-0 z-50">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-4">
    <a href="/" class="flex items-center">
      <img src="/assets/anki-on-rails-logo.png" alt="Logo" class="h-10 mr-2">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Anki on Rails</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= link_to 'Repository', pages_repository_index_path, data: { turbo_frame: @pages_content }, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent' %>
        </li>
        <li>
          <%= link_to 'Contact', pages_contact_index_path, data: { turbo_frame: @pages_content }, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent' %>
        </li>
        <li>
          <%= link_to 'About', pages_about_index_path, data: { turbo_frame: @pages_content }, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent' %>
        </li>       <li>
          <% if current_user %>
            <a href="/logout" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Logout</a>
          <% else %>
            <a href="/login" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Login</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/pages/about/_index.html.erb
<%= turbo_frame_tag @pages_content do %>
  <!-- TODO: Implement about -->
  <p>Cheguei no about</p>
<% end %>

app/views/pages/contact/_index.html.erb
<%= turbo_frame_tag @pages_content do %>
  <!-- TODO: implement contact -->
  <p>Cheguei no contact</p>
<% end %>

app/views/pages/index.html.erb
<%= render 'pages/header' %>

<%= turbo_frame_tag @pages_content do %>
  <hero class="flex flex-col place-items-center">
    <h1 class="font-bold text-3xl mt-20 mb-8">Anki on Rails</h1>
    <h2 class="font-semibold text-6xl text-center"><%= t("home.hero_top") %></h2>
    <p class="text-2xl text-center text-gray-600 my-8"><%= t("home.hero_bottom") %></p>
    <%= link_to 'Get Started', new_user_session_path, class: 'inline-flex items-center bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition duration-150 ease-in-out px-6 py-3' %>
  </hero>
  <features>
    <hr class="border-gray-200 sm:mx-auto dark:border-gray-700 my-8 lg:my-10" />
    <!-- TODO: Add features when ready -->
  </features>
  <community class="flex">
    <hr class="border-gray-200 sm:mx-auto dark:border-gray-700 my-8 lg:my-10" />
    <div>
      <!-- TODO: Add community image-->
    </div>
    <div>
      <h1 class="font-bold text-3xl my-6"><%= t('home.community_heading') %></h1>
      <p class="text-gray-500 "><%= t('home.community_body_one') %></p>
      <p class="text-gray-500"><%= t('home.community_body_two') %></p>
      <div class="flex my-6">
        <%= link_to 'Suggestions', new_user_session_path, data: { turbo: false }, class: 'inline-flex items-center bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition duration-150 ease-in-out px-6 py-3' %>
        <%= link_to 'Github', 'https://github.com/petebarbosa/anki-on-rails', class: 'inline-flex items-center bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition duration-150 ease-in-out ml-4 px-6 py-3' %>
      </div>
    </div>
  </community>
  <support class="flex flex-col">
    <hr class="border-gray-200 sm:mx-auto dark:border-gray-700 my-8 lg:my-10" />
    <h1 class="font-bold text-3xl my-6"><%= t('home.support_heading') %></h1>
    <p class="text-gray-500 "><%= t('home.support_body_one') %></p>
    <p class="text-gray-500"><%= t('home.support_body_two') %></p>
  </support>

<% end %>

<%= render 'shared/footer' %>

app/views/pages/repository/_index.html.erb
<%= turbo_frame_tag @pages_content do %>
  <!-- TODO: Implementar repositório -->
  <p>Cheguei nos resources</p>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white rounded-lg shadow dark:bg-gray-900 m-6">
  <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
    <div class="sm:flex sm:items-center sm:justify-between">
      <a href="/" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
        <img src="/assets/anki-on-rails-logo.png" alt="Logo" class="h-10">
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Anki on Rails</span>
      </a>
      <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400">
        <li>
          <%= link_to "Github", "https://github.com/petebarbosa", class: "hover:underline me-4 md:me-6" %>
        </li>
        <li>
          <%= link_to "LinkedIn", "https://www.linkedin.com/in/pvbb250689/", class: "hover:underline" %>
        </li>
      </ul>
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
    <div class="flex sm:justify-center">
      <span class="text-sm text-gray-500 dark:text-gray-400">Developed by <a href="https://www.linkedin.com/in/pvbb250689/" class='hover:underline'>Pete Barbosa</a>, 2024.
    </div>
  </div>
</footer>